[2025-04-01T05:30:13.485+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag2.move_to_transformation manual__2025-04-01T04:30:09.356142+00:00 [queued]>
[2025-04-01T05:30:13.492+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag2.move_to_transformation manual__2025-04-01T04:30:09.356142+00:00 [queued]>
[2025-04-01T05:30:13.493+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-01T05:30:13.505+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): move_to_transformation> on 2025-04-01 04:30:09.356142+00:00
[2025-04-01T05:30:13.508+0100] {standard_task_runner.py:60} INFO - Started process 31237 to run task
[2025-04-01T05:30:13.510+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_dag2', 'move_to_transformation', 'manual__2025-04-01T04:30:09.356142+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/test_dag2.py', '--cfg-path', '/tmp/tmpdgxc05wu']
[2025-04-01T05:30:13.512+0100] {standard_task_runner.py:88} INFO - Job 257: Subtask move_to_transformation
[2025-04-01T05:30:13.557+0100] {task_command.py:423} INFO - Running <TaskInstance: test_dag2.move_to_transformation manual__2025-04-01T04:30:09.356142+00:00 [running]> on host LAPTOP-A4DHQTS9.
[2025-04-01T05:30:13.632+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_dag2' AIRFLOW_CTX_TASK_ID='move_to_transformation' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T04:30:09.356142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T04:30:09.356142+00:00'
[2025-04-01T05:30:13.643+0100] {base.py:83} INFO - Using connection ID 'destination_db' for task execution.
[2025-04-01T05:30:13.650+0100] {sql.py:450} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS transformation.trans_prog3 (LIKE stagimg.stg_prog3);
    , parameters: None
[2025-04-01T05:30:13.651+0100] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/philip/airflow/dags/test_dag2.py", line 87, in move_to_transformation
    dest_pg_hook.run(create_table_query)
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "stagimg" does not exist
LINE 2: ...LE IF NOT EXISTS transformation.trans_prog3 (LIKE stagimg.st...
                                                             ^

[2025-04-01T05:30:13.661+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_dag2, task_id=move_to_transformation, execution_date=20250401T043009, start_date=20250401T043013, end_date=20250401T043013
[2025-04-01T05:30:13.669+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 257 for task move_to_transformation (schema "stagimg" does not exist
LINE 2: ...LE IF NOT EXISTS transformation.trans_prog3 (LIKE stagimg.st...
                                                             ^
; 31237)
[2025-04-01T05:30:13.683+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-01T05:30:13.699+0100] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
