[2025-03-27T13:15:30.236+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.transfer_data manual__2025-03-27T12:15:27.317258+00:00 [queued]>
[2025-03-27T13:15:30.242+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.transfer_data manual__2025-03-27T12:15:27.317258+00:00 [queued]>
[2025-03-27T13:15:30.243+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-27T13:15:30.252+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transfer_data> on 2025-03-27 12:15:27.317258+00:00
[2025-03-27T13:15:30.254+0100] {standard_task_runner.py:60} INFO - Started process 5633 to run task
[2025-03-27T13:15:30.256+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_dag', 'transfer_data', 'manual__2025-03-27T12:15:27.317258+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpaug6ql_y']
[2025-03-27T13:15:30.259+0100] {standard_task_runner.py:88} INFO - Job 94: Subtask transfer_data
[2025-03-27T13:15:30.308+0100] {task_command.py:423} INFO - Running <TaskInstance: test_dag.transfer_data manual__2025-03-27T12:15:27.317258+00:00 [running]> on host LAPTOP-A4DHQTS9.
[2025-03-27T13:15:30.386+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='transfer_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T12:15:27.317258+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T12:15:27.317258+00:00'
[2025-03-27T13:15:30.396+0100] {base.py:83} INFO - Using connection ID 'source_db' for task execution.
[2025-03-27T13:15:30.402+0100] {sql.py:450} INFO - Running statement: SELECT * FROM prog3;, parameters: None
[2025-03-27T13:15:30.404+0100] {sql.py:459} INFO - Rows affected: 30
[2025-03-27T13:15:30.413+0100] {base.py:83} INFO - Using connection ID 'destination_db' for task execution.
[2025-03-27T13:15:30.426+0100] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/philip/airflow/dags/test_dag.py", line 68, in transfer_data
    dest_pg_hook.insert_rows(f"staging.{destination_table}", source_data)
  File "/home/philip/de_engineering/airflow_projects/airflow1/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 541, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.GroupingError: aggregate function calls cannot contain window function calls
LINE 4:         string_agg(format('$%s', row_number() OVER (ORDER BY...
                                         ^
QUERY:  SELECT 
        string_agg(quote_ident(column_name), ', '),
        string_agg(quote_ident(column_name) || ' = EXCLUDED.' || quote_ident(column_name), ', '),
        string_agg(format('$%s', row_number() OVER (ORDER BY column_name)), ', ')
                                                  FROM information_schema.columns
    WHERE table_schema = TG_TABLE_SCHEMA
      AND table_name = TG_TABLE_NAME
      AND column_name NOT IN (id_column, lastupdated_column)
CONTEXT:  PL/pgSQL function utils.update_transformation_table() line 24 at SQL statement

[2025-03-27T13:15:30.436+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_dag, task_id=transfer_data, execution_date=20250327T121527, start_date=20250327T121530, end_date=20250327T121530
[2025-03-27T13:15:30.443+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 94 for task transfer_data (aggregate function calls cannot contain window function calls
LINE 4:         string_agg(format('$%s', row_number() OVER (ORDER BY...
                                         ^
QUERY:  SELECT 
        string_agg(quote_ident(column_name), ', '),
        string_agg(quote_ident(column_name) || ' = EXCLUDED.' || quote_ident(column_name), ', '),
        string_agg(format('$%s', row_number() OVER (ORDER BY column_name)), ', ')
                                                  FROM information_schema.columns
    WHERE table_schema = TG_TABLE_SCHEMA
      AND table_name = TG_TABLE_NAME
      AND column_name NOT IN (id_column, lastupdated_column)
CONTEXT:  PL/pgSQL function utils.update_transformation_table() line 24 at SQL statement
; 5633)
[2025-03-27T13:15:30.470+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-27T13:15:30.486+0100] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
